export const CYCLE_STATUS = {
  PLANNING: 'PLANNING',
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
} as const;

export const PROPOSAL_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
} as const;

export const FUNDING_METHOD = {
  PARTIAL: 'PARTIAL',
  WHOLE: 'WHOLE',
} as const;

export const ROUND_TYPE = {
  SCREENING: 'SCREENING',
  REVIEW: 'REVIEW',
  ACCEPTANCE: 'ACCEPTANCE',
} as const;

export const ROUND_STATUS = {
  PENDING: 'PENDING',
  OPEN: 'OPEN',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
} as const;

export const ROUND_DIMENSION = {
  SCIENCE: 'SCIENCE',
  FINANCE: 'FINANCE',
} as const;

export const DECISION_RESULT = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
} as const;

export const COUNCIL_MEMBER_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
} as const;

export const CONTRACT_STATUS = {
  PENDING_SIGNATURE: 'PENDING_SIGNATURE',
  ACTIVE: 'ACTIVE',
  UNDER_REVIEW: 'UNDER_REVIEW',
  COMPLETED: 'COMPLETED',
  TERMINATED: 'TERMINATED',
} as const;

export const DISBURSEMENT_STATUS = {
  PENDING: 'PENDING',
  DISBURSED: 'DISBURSED',
} as const;

export const DELIVERABLE_STATUS = {
  PENDING: 'PENDING',
  SUBMITTED: 'SUBMITTED',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
} as const;

export const MEETING_PLATFORM = {
  IN_PERSON: 'IN_PERSON',
  ONLINE: 'ONLINE',
  HYBRID: 'HYBRID',
} as const;

export const MEETING_STATUS = {
  SCHEDULED: 'SCHEDULED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const PROGRESS_REPORT_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
} as const;

export const FINAL_REPORT_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  ACCEPTED: 'ACCEPTED',
  ARCHIVED: 'ARCHIVED',
} as const;

export const SETTLEMENT_STATUS = {
  DRAFT: 'DRAFT',
  SIGNED: 'SIGNED',
  ACCOUNTING_CLEARED: 'ACCOUNTING_CLEARED',
  ASSETS_CLEARED: 'ASSETS_CLEARED',
  COMPLETED: 'COMPLETED',
} as const;

export const AMENDMENT_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const MEMBER_ROLE_CODE = {
  CNNV: 'CNNV',
  TKKH: 'TKKH',
  TVC: 'TVC',
  TV: 'TV',
  KTV: 'KTV',
} as const;

export const COUNCIL_MEMBER_ROLE = {
  CHAIRMAN: 'CHAIRMAN',
  SECRETARY: 'SECRETARY',
  MEMBER: 'MEMBER',
  ORDERING_PARTY_REP: 'ORDERING_PARTY_REP',
} as const;

export const COUNCIL_STAGE = {
  PROPOSAL: 'PROPOSAL',
  FINAL_REPORT: 'FINAL_REPORT',
} as const;

export const RESEARCH_TYPE_CODE = {
  APPLIED: 'APPLIED',
  PAPER: 'PAPER',
} as const;

export const APPLIED_TOPIC_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
} as const;

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;

export const NOTIFICATION_TYPE = {
  PROPOSAL_SUBMITTED: 'PROPOSAL_SUBMITTED',
  PROPOSAL_APPROVED: 'PROPOSAL_APPROVED',
  PROPOSAL_REJECTED: 'PROPOSAL_REJECTED',
  ROUND_OPENED: 'ROUND_OPENED',
  ROUND_CLOSED: 'ROUND_CLOSED',
  COUNCIL_INVITATION: 'COUNCIL_INVITATION',
  MEETING_SCHEDULED: 'MEETING_SCHEDULED',
  CONTRACT_CREATED: 'CONTRACT_CREATED',
  DELIVERABLE_DUE: 'DELIVERABLE_DUE',
  DELIVERABLE_OVERDUE: 'DELIVERABLE_OVERDUE',
  DISBURSEMENT_RELEASED: 'DISBURSEMENT_RELEASED',
  PROGRESS_REPORT_DUE: 'PROGRESS_REPORT_DUE',
  FINAL_REPORT_ACCEPTED: 'FINAL_REPORT_ACCEPTED',
  GENERAL: 'GENERAL',
} as const;
